### ISSUE TITLE
Error when attempting to read results.json file for .NET project

### ISSUE THREAD

**Issue by kylemaestro** [veracode/veracode-pipeline-scan-results-to-sarif#17]
Hi, I'm utilizing the pipeline scan .jar from pipeline-scan-LATEST.zip to run a pipeline scan of a .NET project. I can see the uploaded artifact after the scan has been run that's named "results.json", and opening the file reveals some issues that were found. This step is working fine, but when I try to use this action with the generated results.json file I get the following error:

`Cannot read property 'TestResults' of undefined`

Surprisingly, the log statement immediately preceding the error above is:

`Pipeline Scan results file found and parsed - validated JSON file`

"TestResults" predictably does not appear in my results.json file, but glancing through the source code for this action I can't find any mention of "TestResults" either. My best guess is that this is coming from Converter.ts line 159, but I'm not super familiar with TypeScript/JavaScript so it's all greek to me. Any ideas?

For reference, here is the raw results.json output:
https://pastebin.com/ixQaJeHe

**Comment by Piszmog** [comment]
I had to use master instead of a tag to get the action to work

**Comment by kylemaestro** [comment]
I unfortunately don't have access to the original results json file anymore. I managed to resolve this issue _somehow_ but it's been so long I can't remember what I did... Safe to say it's probably something I was doing wrong unless anyone else has seen this exact sequence of logs before.
