### ISSUE TITLE
Update SARIF JSON schema location

### ISSUE THREAD

**Issue by thomas-chauchefoin-bentley-systems** [veracode/veracode-pipeline-scan-results-to-sarif#42]
The schema isn't at https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json anymore, but https://raw.githubusercontent.com/oasis-tcs/sarif-spec/refs/heads/main/sarif-2.1/schema/sarif-schema-2.1.0.json.

**Comment by jsoref** [comment]
Fwiw, they promise to keep https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json as a somewhat reliable URL (I tripped on this too)

**Comment by thomas-chauchefoin-bentley-systems** [comment]
Thanks!
